### PR TITLE
Check if the rotator is hidden, if yes, flip to the other side

### PR DESCRIPTION
**Pull request by juliaroldi**
If the rotator handle is at the top or in left side at the editor or is overlaid by the border or the rotator handle overlays the resize handle. 

**Before:**
rotatorBugsBefore

**After:**
rotatorBugs

### CODE REVIEW

**Comment by JiuqingSong** [comment]
This is interesting. With this fix, I think you can remove the code to auto-lower-down the rotate handle to make it consistent.

**Comment by juliaroldi** [comment]
> This is interesting. With this fix, I think you can remove the code to auto-lower-down the rotate handle to make it consistent.

I think it is better to let this feature, because if this user is dragging next to the top, the experience will be better. If the user drag the rotator very near the top, the rotator will be overlayed by the border.

**Comment by JiuqingSong** [comment]
> > This is interesting. With this fix, I think you can remove the code to auto-lower-down the rotate handle to make it consistent.
> 
> I think it is better to let this feature, because if this user is dragging next to the top, the experience will be better. If the user drag the rotator very near the top, the rotator will be overlayed by the border without this feature. I think would be nice if we also add to detect the left side.

I mean when image is at the top of editor and rotate it, today we have code to auto lower the rotation handle:

image

compare to:

image

With this change, that feature is no needed any more since we will show resize handle at the bottom instead. You can remove the old code.

**Comment by juliaroldi** [comment]
> > > This is interesting. With this fix, I think you can remove the code to auto-lower-down the rotate handle to make it consistent.
> > 
> > 
> > I think it is better to let this feature, because if this user is dragging next to the top, the experience will be better. If the user drag the rotator very near the top, the rotator will be overlayed by the border without this feature. I think would be nice if we also add to detect the left side.
> 
> I mean when image is at the top of editor and rotate it, today we have code to auto lower the rotation handle:
> 
> image
> 
> compare to:
> 
> image
> 
> With this change, that feature is no needed any more since we will show resize handle at the bottom instead. You can remove the old code.

I think if the user is dragging near the top, without clicking out of the rotator, the experience will be better, but I don't mind to remove it.

**Pull request closed without merging**
