### PR TITLE
[Feat] Support excluding elements from being transformed

### PR DESCRIPTION
**Pull request by haven2world**
We have some features which we want to set the style under dark mode by ourselves. So we need to add this method to make it possiblie.

Before we achieved it by the API `onExternalContentTransform` which has been deprecated and not used in code.

### CODE REVIEW

**Comment by haven2world** [comment]
Hi @JiuqingSong do you know how to revert the change of EOL?

**Comment by JiuqingSong** [comment]
Would you please help me understand what kind of customization you want to do when do color transform? I'd like to put all dark color related logic into DarkColorHandler. So your requirement can help me decide how to design it.

**Comment by haven2world** [comment]
Sure. For example we have a feature to beautify the link, and we will keep the same style of the link when the dark mode changes. And for another feature, we just prefer to set the style by ourselves when dark mode changes, rather than calculating it automatically.

**Comment by haven2world** [comment]
> Hi @JiuqingSong do you know how to revert the change of EOL?

Fixed it by remaking the change on windows

**Comment by haven2world** [comment]
@JiuqingSong We cannot bump roosterJS version until this change is released. Any concern to merge this?

**Comment by JiuqingSong** [comment]
Instead of adding a new option, we'd better still reuse the `onExternalContentTransform` option. We should avoid add more and more options when there is already another one can do the same job.

**Comment by haven2world** [comment]
Sure, if possible. But currently `onExternalContentTransform` is deprecated and in the code, it's not called anymore. And on the other hand, we also want to leverage the internal implementation of dark mode transform, rather than we implement it again in `onExternalContentTransform` but the internal implementation doesn't provide a way to exclude some elements which I think is helpful and necessary.

**Comment by haven2world** [comment]
That's great! It's good to know we're going to have a new dark mode manager.
Sure. I'll close this PR. Thanks for your help!

**Pull request closed without merging**
