### PR TITLE
Return the Table Operation in the editTable API and store it in the Content Edit Event Data

### PR DESCRIPTION
**Pull request by BryanValverdeU**
Store the content edit data when editing a table, so this information can be used during the content changed event.

### CODE REVIEW

**Comment by JiuqingSong** [comment]
is this for logging?

**Comment by BryanValverdeU** [comment]
Yes it can be used for logging, but the mail reason I am adding it is to use it in the Content Changed event so we can announce to the user that a new row has been added.

**Comment by JiuqingSong** [comment]
> Yes it can be used for logging, but the main reason I am adding it is to use it in the Content Changed event so we can announce to the user that a new row has been added.

I see. I think it is ok to do this for now. But we more and more kind of data added to ContentChangedEvent, and they are not strong-typed, it will be hard to manage in the future. I think later we may need to design a unified way to let plugins know what kind of change it happened.

**Review by JiuqingSong — APPROVED** [review]

**Comment by BryanValverdeU** [comment]
Marking this as Draft for now.

**Pull request closed without merging**
