### PR TITLE
Fix(#1201): Table selection when <th> and <td> in the same row

### PR DESCRIPTION
**Pull request by StephenArk30**
Check [nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) selector. No need to consider the tag name when using this selector.

### CODE REVIEW

**Comment by JiuqingSong** [comment]
@BryanValverdeU would you please help review this change?

@StephenArk30  Thanks for make the fix. Would you please also add test case for the fix?

**Review by BryanValverdeU — APPROVED** [review]
Looks good to me. Thanks for the fix.

**Comment by StephenArk30** [comment]
> Looks good to me. Thanks for the fix. Please add a unit test for this scenario

ok

**Comment by StephenArk30** [comment]
Done. Is that enough?

**Review by JiuqingSong — APPROVED** [review]

**Pull request merged**
