### PR TITLE
Recreate Content Model for table and image selection

### PR DESCRIPTION
**Pull request by JiuqingSong**
With advanced cache enabled in Content Model editor, when we start a table selection, table id can be modified. When that happens, we need to update cached model to reflect this change.

For now the easiest way is to clear cache and rebuild content model when new selection is table/image.

### CODE REVIEW

**Review by juliaroldi — APPROVED** [review]

**Comment by juliaroldi** [comment]
How table/image id can be changed during compose? Are we changing this this because of particular bug?

**Comment by JiuqingSong** [comment]
> How table/image id can be changed during compose? Are we changing this this because of particular bug?

https://github.com/microsoft/roosterjs/blob/b6f69616f7b14266ef6347bd856c8e7a34da8970/packages/roosterjs-editor-core/lib/coreApi/selectTable.ts#L40

If the selected image or table does not have id (it is the common case), we add id to it when select.

**Comment by juliaroldi** [comment]
> > How table/image id can be changed during compose? Are we changing this this because of particular bug?
> 
> https://github.com/microsoft/roosterjs/blob/b6f69616f7b14266ef6347bd856c8e7a34da8970/packages/roosterjs-editor-core/lib/coreApi/selectTable.ts#L40
> 
> If the selected image or table does not have id (it is the common case), we add id to it when select.

I understood by the PR description that if the table/image that has id might have it modified.

**Comment by JiuqingSong** [comment]
> > > How table/image id can be changed during compose? Are we changing this this because of particular bug?
> > 
> > 
> > https://github.com/microsoft/roosterjs/blob/b6f69616f7b14266ef6347bd856c8e7a34da8970/packages/roosterjs-editor-core/lib/coreApi/selectTable.ts#L40
> > 
> > If the selected image or table does not have id (it is the common case), we add id to it when select.
> 
> I understood by the PR description that if the table/image that has id might have it modified.

If there is already id, and it is unique, then it won't be changed. In theory we can check whether it is changed, but it need to go through the whole model to find the table, so just clear the cached model should be easier. This is not ideal, but it should fix a blocker issue for enabling cache. Later I may find a better way.

**Pull request merged**
