### PR TITLE
fix：when toggle list type,list symbol style maybe incorrect

### PR DESCRIPTION
**Pull request by JingweiXiong**
## Question

https://user-images.githubusercontent.com/19570679/187584487-8a148666-4262-4b95-b41f-e51d5d27bfa2.mov

In some case such as li>b>text, list symbol style is incorrect

## After resolved

https://user-images.githubusercontent.com/19570679/187584606-fa79cddc-8328-4b0c-af06-f03948fc8213.mov

Thanks.

### CODE REVIEW

**Comment by JiuqingSong** [comment]
@juliaroldi  @BryanValverdeU  would you please review this change? Thanks.

**Comment by juliaroldi** [comment]
@JingweiXiong Hey, I tried you change, at least for me, the feature does not work, if the first element does not have any change in the styles. 
TestingListgif

**Comment by juliaroldi** [comment]
@JingweiXiong 
TestingListgif2

**Comment by JingweiXiong** [comment]
@juliaroldi @JiuqingSong  Sorry. It's my problem. I moved here after my project was test successful, but i miss VListItem.ts.

**Comment by juliaroldi** [comment]
> @juliaroldi @JiuqingSong Sorry. It's my problem. I moved here after my project was test successful, but i miss VListItem.ts.

Hey @JingweiXiong, that is not a problem. @BryanValverdeU fixed the missing code and we already merged your fix into our codebase. Thanks for contribute to RoosterJS!

**Pull request merged**
