### PR TITLE
FHL: Port TableCellSelection plugin

### LINKED ISSUE #861: TableCellSelection Plugin is not considering the Cell Spans
**Describe the bug**
When selecting the tables we are not considering the Table Spans, which cause weird behaviors in tables with merged cells.

Eg
image

Vs Word
image

### PR DESCRIPTION
**Pull request by JiuqingSong**
Port the original `TableCellSelection` plugin and merge the logic into existing `SelectionPlugin`. Now the table selection become part of editor core, and no need to add any plugin explicitly for it.

Expose the following new types:

- TableCellCoordinate: {row, col}
- TableSelectionInfo: Store current table selection info, can be incomplete since user is still moving mouse
- ParsedTable: a 2D array for TD or its span state

Create the following internal util functions:

- findTableCellElement: Try to find a TD/TH element from the given row and col number from the given parsed table
- findLastedCoInMergedCell: Try to find the last logic cell of a merged table cell
- findCoordinate: Find coordinate of a given element from a parsed table
- normalizePos: Find the deepest position of the given position (aka Position.normalize() in old code)

Add a `IgnoredPluginNames` const in `EditorAdapter` to aways ignore old `TableCellSelection` plugin since it will be conflict with the new one

Also handle keyboard event for the following cases:
- Up/Down in table: move focus into the cell above/below
- Shift+Up/Down in table: select current cell and the cell above/below. If there is already table selection, adjust the selection according to the key
- Shift+Left/Right in table: select current cell and the cell left/right. If there is already table selection, adjust the selection according to the key

I didn't handle TAB key in this change since it is not directly related to table selection. We will handle it in future changes.

Fix a bug in `getDOMSelection` when check isReverted.
Fix #861

### CODE REVIEW

**Comment by Andres-CT98** [comment]
This behaviour appears to be missing from the port: #2024

**Comment by JiuqingSong** [comment]
> This behaviour appears to be missing from the port: #2024

Thanks, good catch! Just fixed.

**Comment by BryanValverdeU** [comment]
If I start a selection in a nested table and mouse move to the parent table, the selection is not updating to the parent table. Not sure if we want to implement in the new plugin:

**Comment by JiuqingSong** [comment]
> If I start a selection in a nested table and mouse move to the parent table, the selection is not updating to the parent table. Not sure if we want to implement in the new plugin:  [  ](https://private-user-images.githubusercontent.com/8291124/314208660-8a17953f-97d2-4f7f-8a57-ddb3bd0d6277.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODg1MzcsIm5iZiI6MTcxMDg4ODIzNywicGF0aCI6Ii84MjkxMTI0LzMxNDIwODY2MC04YTE3OTUzZi05N2QyLTRmN2YtOGE1Ny1kZGIzYmQwZDYyNzcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMjI0MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ4ZWZlZTQwZDc1NGVkNzBhNTYwZDJmMGIxNGEyOTc0NTFiNmNmZGYwOWM1NWU1ZjI3MTdhYjg2NWNiN2NmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zsCG5w8qgDMpRZ6A_ZO_Ei1QSrPFsR8e9ne7-Mc13T0) [ ](https://private-user-images.githubusercontent.com/8291124/314208660-8a17953f-97d2-4f7f-8a57-ddb3bd0d6277.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODg1MzcsIm5iZiI6MTcxMDg4ODIzNywicGF0aCI6Ii84MjkxMTI0LzMxNDIwODY2MC04YTE3OTUzZi05N2QyLTRmN2YtOGE1Ny1kZGIzYmQwZDYyNzcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMjI0MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ4ZWZlZTQwZDc1NGVkNzBhNTYwZDJmMGIxNGEyOTc0NTFiNmNmZGYwOWM1NWU1ZjI3MTdhYjg2NWNiN2NmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zsCG5w8qgDMpRZ6A_ZO_Ei1QSrPFsR8e9ne7-Mc13T0)

Thanks, fixed.

**Review by BryanValverdeU — APPROVED** [review]

**Pull request merged**
