### PR TITLE
fix: toggling inner list type

### PR DESCRIPTION
**Pull request by tshibley**
fixing a bug where list style type was applied to inner lists even when the type was toggled

https://github.com/microsoft/roosterjs/issues/1256

### CODE REVIEW

**Comment by BryanValverdeU** [comment]
Thank you for the fix.
It seems like the issue is only happening when toggling the list, so I think we can add a new member property 
VListItem 'wasListTypeToggled' and update this member property to true in changeListType function.
https://github.com/microsoft/roosterjs/blob/0e9b92f7a0293064bce24049f08190dfeba42526/packages/roosterjs-editor-dom/lib/list/VListItem.ts#L223-L237

Then we can use the new property and if it is true, do not modify the list style type of the new list.

@JiuqingSong do you think adding this new member for this scenario is okay?

**Comment by tshibley** [comment]
@BryanValverdeU Thanks for taking a look! 

I'm not sure I totally follow why we would need to create a special case here for the toggling vs. checking to make sure the tags match any time we writeback. Is there a time when we still want to override the list type with marker of a different type? (Such that an `ol` has a bullet marker for instance)

**Comment by BryanValverdeU** [comment]
Got it, you are right. 
I was able to test the functionality and it is working fine.

Thanks for the fix

**Review by BryanValverdeU — APPROVED** [review]

**Comment by tshibley** [comment]
Great, thanks!

**Pull request merged**
