### PR TITLE
fix wrap content when element is empty

### PR DESCRIPTION
**Pull request by FrancisMengx**

### CODE REVIEW

**Review by JiuqingSong — APPROVED** [review]

**Comment by biubiubiu-boom** [comment]
What's the reason to add a `<br/>` into an empty node? @JiuqingSong  @FrancisMengx

**Comment by JiuqingSong** [comment]
> What's the reason to add a `<br/>` into an empty node? @JiuqingSong @FrancisMengx image

Browser can't put cursor into empty `<DIV></DIV>`, which makes some other code not working correctly.

**Comment by biubiubiu-boom** [comment]
Thanks for the explanation @JiuqingSong . I have another question: if I added some empty elements (not only the div) as a flag into editor, would those elements contain a `<br/>` as a child element and show a blank line in editor too?

**Comment by JiuqingSong** [comment]
If it is intentional invisible, then no need to add BR

**Pull request merged**
